stages:
  fetch_data:
    cmd: python scripts/fetch_data.py
    deps:
      - scripts/fetch_data.py
    outs:
      - data/raw/raw_data.csv
  preprocess_data:
    cmd: python scripts/preprocess_data.py
    deps:
      - scripts/preprocess_data.py
      - data/raw/raw_data.csv
    outs:
      - data/processed/processed_data.csv
  train_model:
    cmd: python scripts/train_model.py
    deps:
      - scripts/train_model.py
      - data/processed/processed_data.csv
    outs:
      - models/model.pkl
